name: yijueun_jueun
description: A sample command-line application.

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.3
  google_sign_in: ^5.4.2
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.0.3

flutter:
  uses-material-design: true